name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref}}

on:
  workflow_dispatch: {}
  push:
    branches:
      - test

jobs:
  ci_debugger:
    runs-on:
      - X64
    steps:
      - name: Template
        run: |
          echo "hello, world"
      - name: Set ssh pub key
        run: |
          curl https://github.com/${{github.actor}}.keys > ~/.ssh/temp_keys
          cp -rf ~/.ssh/temp_keys ~/.ssh/authorized_keys
          ls -al ~/.ssh
      - name: Check docker version
        run: |
          docker --version
        continue-on-error: true

      - name: Install docker (if failed)
        if: failure()
        run: |
          curl -fsSL https://get.docker.com | sh

      - name: Checkout
        uses: actions/checkout@v4
